export const destinations=[
 {slug:"caribbean",name:"Caribbean",season:"October–April",days:"7–12 nights",intro:"Turquoise water, bright island culture, and easy days beneath the sun.",ports:["Miami","Nassau","St. Thomas","Ocean Cay"],highlights:["Reef snorkeling","Old San Juan walk","Private beach day"]},
 {slug:"alaska",name:"Alaska",season:"May–September",days:"7–14 nights",intro:"Glaciers, wildlife, and immense coastal landscapes viewed from the water.",ports:["Vancouver","Juneau","Skagway","Ketchikan"],highlights:["Glacier Bay","Whale watching","White Pass railway"]},
 {slug:"mediterranean",name:"Mediterranean",season:"April–October",days:"8–14 nights",intro:"Ancient cities, celebrated food, and sun-washed shores in one voyage.",ports:["Barcelona","Marseille","Rome","Santorini"],highlights:["Roman landmarks","Aegean villages","Market tasting"]},
 {slug:"northern-europe",name:"Northern Europe",season:"May–September",days:"10–16 nights",intro:"Fjords, design capitals, and long summer evenings across the north.",ports:["Southampton","Bergen","Tromsø","Copenhagen"],highlights:["Norwegian fjords","Northern lights","Nordic architecture"]},
 {slug:"panama-canal",name:"Panama Canal",season:"October–April",days:"10–16 nights",intro:"A landmark transit connecting tropical coasts and engineering history.",ports:["Miami","Cartagena","Colón","Puntarenas"],highlights:["Full canal transit","Old Cartagena","Rainforest tram"]},
 {slug:"south-pacific",name:"South Pacific",season:"November–March",days:"12–21 nights",intro:"Remote islands, volcanic horizons, and slow days on warm blue water.",ports:["Sydney","Nouméa","Suva","Papeete"],highlights:["Lagoon sailing","Island welcome","Volcanic landscapes"]},
 {slug:"world-voyage",name:"World Voyage",season:"January departure",days:"90–120 nights",intro:"A sweeping collection of continents and cultures aboard one ship.",ports:["Southampton","Cape Town","Singapore","Sydney"],highlights:["Overnight cities","Grand events","Extended port stays"]},
 {slug:"transatlantic",name:"Transatlantic",season:"Spring & autumn",days:"7–14 nights",intro:"The classic ocean crossing, with unhurried days and open horizons.",ports:["Southampton","Cobh","New York","Miami"],highlights:["Days at sea","Enrichment program","Historic arrival"]}
];
